#!/usr/bin/env python3
"""Generate a markdown ProofCard from local verifier output."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "proofcards" / "ho-det-001-proofcard.md"
PROOF_CEILING = "SAMPLE_LEVEL_WAZUH_CONTRACT_VALIDATION_ONLY"


def run_verifier() -> dict[str, Any]:
    completed = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "verify_rule_contract.py"), "--format", "json"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    try:
        result = json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"verifier did not emit JSON: {completed.stdout}") from exc
    if completed.returncode != 0 or result.get("status") != "pass":
        raise RuntimeError(f"verifier failed: {result}")
    return result


def bullet_list(items: list[str]) -> str:
    if not items:
        return "- None."
    return "\n".join(f"- {item}" for item in items)


def render(result: dict[str, Any]) -> str:
    not_tested = [
        "Live Wazuh manager execution.",
        "Runtime telemetry routing.",
        "Signal observation.",
        "Production deployment.",
        "Public-safe runtime proof.",
        "Analyst or AI disposition authority.",
    ]
    return f"""# {result['candidate_id']} ProofCard

Generated by `scripts/generate_proofcard.py`.

| Field | Value |
|---|---|
| Candidate ID | {result['candidate_id']} |
| Proof ceiling | {PROOF_CEILING} |
| Validation result | {result['status']} |
| Sample set | {result['sample_set']} |

## What Passed

{bullet_list(result.get("what_passed", []))}

## What Failed

{bullet_list(result.get("what_failed", []))}

## What Was Not Tested

{bullet_list(not_tested)}

## Safe Claims

{bullet_list(result.get("safe_claims", []))}

## Blocked Claims

{bullet_list(result.get("blocked_claims", []))}
"""


def generate(output: Path = DEFAULT_OUTPUT) -> Path:
    result = run_verifier()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(result), encoding="utf-8")
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    try:
        output = generate(args.output)
    except RuntimeError as exc:
        print(json.dumps({"status": "fail", "error": str(exc)}, indent=2), file=sys.stderr)
        return 1
    print(json.dumps({"status": "pass", "proofcard": output.relative_to(ROOT).as_posix()}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
