#!/usr/bin/env python3
"""Generate a markdown ProofCard from local verifier output."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

try:
    import jsonschema
except ImportError:  # pragma: no cover
    jsonschema = None


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "proofcards" / "ho-det-001-proofcard.md"
PROOF_CEILING = "SAMPLE_LEVEL_WAZUH_CONTRACT_VALIDATION_ONLY"
PROOFCARD_SCHEMA = ROOT / "schemas" / "proofcard-v0.schema.json"


def display_path(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def run_verifier() -> dict[str, Any]:
    completed = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "verify_rule_contract.py"), "--format", "json"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    try:
        result = json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"verifier did not emit JSON: {completed.stdout}") from exc
    if completed.returncode != 0 or result.get("status") != "pass":
        raise RuntimeError(f"verifier failed: {result}")
    return result


def run_json_step(command: list[str], allow_nonzero: bool = False) -> dict[str, Any]:
    completed = subprocess.run(command, cwd=ROOT, text=True, capture_output=True, check=False)
    try:
        result = json.loads(completed.stdout)
    except json.JSONDecodeError:
        result = {"status": "fail", "error": completed.stdout or completed.stderr}
    if completed.returncode != 0 and not allow_nonzero:
        result.setdefault("status", "fail")
    return result


def bullet_list(items: list[str]) -> str:
    if not items:
        return "- None."
    return "\n".join(f"- {item}" for item in items)


def render(result: dict[str, Any]) -> str:
    stress_result = run_json_step([sys.executable, "scripts/stress_rule_contract.py", "--format", "json"])
    public_safety_result = run_json_step([sys.executable, "scripts/verify_public_safety.py", "--format", "json"])
    claim_boundary_result = run_json_step([sys.executable, "scripts/verify_claim_boundary.py", "--format", "json"])
    wazuh_result = run_json_step(
        [sys.executable, "scripts/check_wazuh_capability.py", "--format", "json", "--allow-unavailable"],
        allow_nonzero=True,
    )
    wazuh_status = wazuh_result.get("status", "unknown")
    wazuh_bridge = "WAZUH_RUNTIME_BRIDGE_NOT_EXECUTED"
    if wazuh_status == "controlled_logtest_sample_validated":
        wazuh_bridge = "CONTROLLED_WAZUH_LOGTEST_SAMPLE_VALIDATED"
    not_tested = [
        "Live Wazuh manager execution.",
        "Runtime telemetry routing.",
        "Signal observation.",
        "Production deployment.",
        "Public-safe runtime proof.",
        "Analyst or AI disposition authority.",
    ]
    proofcard_data = {
        "candidate_id": result["candidate_id"],
        "proof_ceiling": PROOF_CEILING,
        "validation_result": result["status"],
        "sample_set": result["sample_set"],
        "what_passed": result.get("what_passed", []),
        "what_failed": result.get("what_failed", []),
        "what_was_not_tested": not_tested,
        "safe_claims": result.get("safe_claims", []),
        "blocked_claims": result.get("blocked_claims", []),
    }
    schema_validation = "not_run"
    if jsonschema is not None:
        schema = json.loads(PROOFCARD_SCHEMA.read_text(encoding="utf-8"))
        jsonschema.Draft202012Validator(schema).validate(proofcard_data)
        schema_validation = "pass"
    return f"""# {result['candidate_id']} ProofCard

Generated by `scripts/generate_proofcard.py`.

| Field | Value |
|---|---|
| Candidate ID | {result['candidate_id']} |
| Proof ceiling | {PROOF_CEILING} |
| Validation result | {result['status']} |
| Sample set | {result['sample_set']} |
| Schema validation result | {schema_validation} |
| Mutation/stress result | {stress_result.get('status', 'unknown')} |
| Public safety result | {public_safety_result.get('status', 'unknown')} |
| Claim boundary result | {claim_boundary_result.get('status', 'unknown')} |
| Wazuh capability status | {wazuh_status} |
| Wazuh bridge result | {wazuh_bridge} |

## Validation Commands

- `py scripts\\verify_rule_contract.py --format json`
- `py scripts\\stress_rule_contract.py --format json`
- `py scripts\\verify_claim_boundary.py --format json`
- `py scripts\\verify_public_safety.py --format json`
- `py scripts\\check_wazuh_capability.py --format json --allow-unavailable`

## Sample Files

- `{result['positive']['path']}`
- `{result['negative']['path']}`
- `{result['expected_result_path']}`

## What Passed

{bullet_list(result.get("what_passed", []))}

## What Failed

{bullet_list(result.get("what_failed", []))}

## What Was Not Tested

{bullet_list(not_tested)}

## Safe Claims

{bullet_list(result.get("safe_claims", []))}

## Blocked Claims

{bullet_list(result.get("blocked_claims", []))}

## Promotion Requirements

- Controlled sanitized `wazuh-logtest` execution is required before the ceiling can move to `CONTROLLED_WAZUH_LOGTEST_SAMPLE_VALIDATED`.
- blocked: runtime, signal, production, SOC deployment, public-safe runtime proof, analyst approval, AI disposition authority, case closure, customer deployment, and enterprise validation remain unsupported.
"""


def generate(output: Path = DEFAULT_OUTPUT) -> Path:
    result = run_verifier()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(result), encoding="utf-8")
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    try:
        output = generate(args.output)
    except RuntimeError as exc:
        print(json.dumps({"status": "fail", "error": str(exc)}, indent=2), file=sys.stderr)
        return 1
    print(json.dumps({"status": "pass", "proofcard": display_path(output)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
